### ISSUE TITLE
Support Foobar2000 v2.0 major update

### ISSUE THREAD

**Issue by RangerCD** [RangerCD/foo-cad-plus#2]
TODO:
- [x] 64-bit support
- [x] Latest SDK
- [x] Compatibility tests

**Comment by adriaanjelle** [comment]
Please update the plugin for 2.0!

**Comment by adriaanjelle** [comment]
Thank you so much!

**Comment by OrbXXX** [comment]
Thank you so much. As little as it may seems, it brings a lot of joy !
