### ISSUE TITLE
Certain variables missing after install

### ISSUE THREAD

**Issue by cracktorio** [RangerCD/foo-cad-plus#5]
it seems like the title, album art, and song lenght aren't being displayed after i installed it.

**Comment by RangerCD** [comment]
Please provide more information for troubleshooting:

1. System version (Win+R, run `winver`)
2. Foobar2000 version
3. Which application are you using for displaying (SAO Utils/Rainmeter/others)

Screenshots would be helpful if possible.

**Comment by cracktorio** [comment]
windows 11 22H2
foobar v2.1
Rainmeter

**Comment by cracktorio** [comment]
![image](https://github.com/RangerCD/foo-cad-plus/assets/105729942/132b75ed-aaf7-479a-ba87-1078007b34d9)

**Comment by RangerCD** [comment]
I've tested with the official example skin at the end of [doc page](https://docs.rainmeter.net/manual/measures/nowplaying/), and everything seems to be working well.

![image](https://github.com/RangerCD/foo-cad-plus/assets/6872198/78b70134-0866-49b6-b73b-5ec3a3b22673)

Maybe you are experiencing misconfiguration, here are some pieces of advice:
- Make sure foo-cad-plus is loaded (Foobar2000->File->Preferences->Components)
- Make sure your Rainmeter skin is correctly configured (follow the doc above), especially `PlayerName=CAD`, which should be set manually for a downloaded skin pack
